datasource: diary

spring:
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/${datasource}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1928636341@qq.com
    password: gftszmrbwgtocbab
    default-encoding: utf-8

server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    com:
      dq:
        daoyuan: debug
mybatis:
  mapper-locations: classpath*:mapper/*.xml
